# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'deploy.sh']
markdown: rdiscount

# configuration required for some pages

domain: www.dojosp.org
title: Coding Dojo@SP
email: 

# configuration for ehancements, uncomment to enable

feedburner:
  id: DojoSP

google_analytics:
  account: 

# github:
#   username: ghusername

disqus:
  id: dojospblog
